server {
    listen 80;
    listen [::]:80;
    server_name dev.usdm.com.ua;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        return 301 https://dev.usdm.com.ua$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name dev.usdm.com.ua;

    ssl_certificate /etc/letsencrypt/live/dev.usdm.com.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.usdm.com.ua/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    include /etc/nginx/includes/contact_rate_guard.conf;

    location / {
        proxy_pass http://usdm-dev:8000;
        include /etc/nginx/includes/proxy_common.conf;
    }
}
