server {
    listen 80;
    listen [::]:80;
    server_name dev.usdm.ua;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    location / {
        proxy_pass http://usdm-dev:8000;
        include /etc/nginx/includes/proxy_common.conf;
    }
}

